### ISSUE TITLE
Milestone 2 fixes

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/universal-dot-front-end#18]
- [x] Fix tests
- [x] Add class selectors to components to easily target tests
- [x] Add basic input validation (client side)
- [x] `yarn npm audit` issues security warnings

All fixes should be done on this branch: https://github.com/UniversalDot/universal-dot-front-end/tree/feat/milestone2-fixes
